name: The Australian Actor
favicon: null
layout_spectrum: 0.85274
typography_spectrum: 0.65466
title: The Australian Actor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d2c34'
    - '#fbffff'
    - '#b8b0b1'
    - '#dbd0cc'
    - '#6a7467'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.4087716236244887
  rhythmicContrast: 0.28187659941613674
purpose: []
